plugins {
    id "com.gradleup.shadow" version "9.3.0"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    Project common = project(":common")
    accessWidenerPath = common.loom.accessWidenerPath

    runs {
        datagen {
            client()

            name "Minecraft Data"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${common.file("src/generated/resources")}"
            vmArg "-Dfabric-api.datagen.modid=${archives_base_name}"
            programArgs "--existing", file("src/main/resources").absolutePath

            environmentVariable("DATAGEN", "TRUE")
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    // Remove the next line if you don't want to depend on the API
    //modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    // FD Refabricated
    modImplementation ("vectorwing:FarmersDelight:${fdrf_version}") {
        exclude(group: "net.fabricmc")
    }

    // MidnightLib
    modImplementation include("maven.modrinth:midnightlib:${project.midnightlib_fabric_version}")

    // ModMenu
    modLocalRuntime("com.terraformersmc:modmenu:${mod_menu_version}")

    // Recipe Viewers
    // EMI
    modCompileOnly("dev.emi:emi-fabric:$emi_version:api") {
        transitive = false
        exclude(group: "net.fabricmc.fabric-api")
    }
    // JEI
    modCompileOnly("mezz.jei:jei-$minecraft_version-common-api:$jei_version") { transitive = false }
    modCompileOnly("mezz.jei:jei-$minecraft_version-fabric-api:$jei_version") { transitive = false }
    // REI
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-api-fabric:$rei_version") { transitive = false }
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:$rei_version")

    // RRV
    modCompileOnly("maven.modrinth:rrv:${rrv_version}-fabric") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    switch (recipe_viewer.toLowerCase(Locale.ROOT)) {
        case "jei": modLocalRuntime("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"); break
//        case "rei": modLocalRuntime("me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"); break
        case "emi": modLocalRuntime("dev.emi:emi-fabric:${emi_version}"); break
        case "rrv": modLocalRuntime("maven.modrinth:rrv:${rrv_version}-fabric") {exclude(group: "net.fabricmc.fabric-api")}; break
        case "disabled": break
        default: println("Unknown recipe viewer specified: ${recipe_viewer}. Must be JEI, REI, EMI, RRV, or disabled.")
    }

    // compile against the API
    modCompileOnly "mcp.mobius.waila:wthit-api:fabric-${wthitVersion}"

    // run against the full jar
    modRuntimeOnly "mcp.mobius.waila:wthit:fabric-${wthitVersion}"
    modRuntimeOnly "lol.bai:badpackets:fabric-${badpacketsVersion}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }

    // Integration Testing
    // Fabric Seasons
    //modLocalRuntime("maven.modrinth:fabric-seasons:2.3+1.20")
    //modLocalRuntime("maven.modrinth:fabric-seasons-delight-compat:1.0")
}

processResources {
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar

}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}

def buildSuffix = mod_version_type != "STABLE" ? "-${mod_version_type}" + (mod_build_number != "0" ? "-${mod_build_number}" : "") : ""
version = "${project.name}-${minecraft_version}-${mod_version}${buildSuffix}"

var changelogFile = rootProject.file("changelog.md")
var changelogText = changelogFile.exists() ? changelogFile.text : ""
var vName = mod_name + " " + project.version

publishMods {
    file = remapJar.archiveFile
    changelog = changelogText
    version = project.version
    type = mod_version_type
    displayName = vName

    modLoaders.add("fabric")
    modLoaders.add("quilt")

    curseforge("curseforgeFabric") {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = curseforge_project_id

        minecraftVersions.addAll(minecraft_supported_versions.split(","))
        javaVersions.add(JavaVersion.VERSION_21)

        clientRequired = true
        serverRequired = true

        requires("fabric-api")
        requires("farmers-delight-refabricated")
        embeds("midnightlib")
        optional("modmenu")
        optional("jei")
        optional("roughly-enough-items")
        optional("emi")
        optional("rrv")
    }

    modrinth("modrinthFabric") {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = modrinth_project_id

        minecraftVersions.addAll(minecraft_supported_versions.split(","))

        requires("fabric-api")
        requires("farmers-delight-refabricated")
        embeds("midnightlib")
        optional("modmenu")
        optional("jei")
        optional("rei")
        optional("emi")
        optional("rrv")
    }
}