org.gradle.jvmargs = -Xmx2048M

# Minecraft Versions
minecraft_version = 1.21.8
minecraft_min_version = 1.21.6
minecraft_max_version = 1.21.8

# Mod Info
mod_id = ubesdelight
mod_name = Ube's Delight
mod_version = 0.4.7
mod_license = MIT
mod_authors = ChefMooon
mod_description = An addon mod for Farmer's Delight that adds Filipino inspired crops and food.
mod_homepage = https://github.com/ChefMooon/ubes-delight/wiki
mod_issues = https://github.com/ChefMooon/ubes-delight/issues
mod_github = https://github.com/ChefMooon/ubes-delight
mod_discord = https://discord.gg/mbuDBHHUws
mod_credits = ChefMooon, potatomadz

minecraft_supported_versions = 1.21.6,1.21.7,1.21.8
# STABLE, BETA, ALPHA
mod_version_type = STABLE
mod_build_number = 0
modrinth_project_id = PYjpoAys
curseforge_project_id = 903894

archives_base_name=ubesdelight
maven_group=com.chefMooon.ubesdelight

# Architectury
enabled_platforms = fabric
architectury_version = 9.1.12

parchment_version = 1.21.8:2025.09.14

fabric_loader_version = 0.16.14
fabric_api_version = 0.129.0+1.21.8

neoforge_version = 21.1.82
#1.20.1-47.2.1

# Farmer's Delight
fdrf_version = 1.21.8-3.3.2+refabricated
farmersdelight_version = 5962800

# Recipe Viewer Compat
# JEI, REI, EMI, EIV, or disabled
recipe_viewer = disabled
# https://modrinth.com/mod/jei/versions
jei_version = 19.9.0.121
# https://modrinth.com/mod/rei/versions
rei_version = 20.0.811
# https://modrinth.com/mod/emi/versions
emi_version = 1.1.12+1.21
# https://modrinth.com/mod/eiv
eiv_version = 4.1.0

# Appleskin
appleskin_fabric_version = mc1.21.6-3.0.7
appleskin_neoforge_version = mc1.21.6-3.0.7

# MidnightLib
midnightlib_fabric_version = 1.7.5+1.21.6-fabric
midnightlib_neoforge_version = 1.7.5+1.21.6-neoforge

# Mod Menu
mod_menu_version = 15.0.0

# WTHIT
wthitVersion = 16.0.4
badpacketsVersion = 0.9.0