org.gradle.jvmargs = -Xmx2048M

# Minecraft Versions
minecraft_version = 26.1.2
minecraft_min_version = 26.1
minecraft_max_version = 26.1.2

# Mod Info
mod_id = ubesdelight
mod_name = Ube's Delight
mod_version = 0.4.11
mod_license = MIT
mod_authors = ChefMooon
mod_description = An addon mod for Farmer's Delight that adds Filipino inspired crops and food.
mod_homepage = https://github.com/ChefMooon/ubes-delight/wiki
mod_issues = https://github.com/ChefMooon/ubes-delight/issues
mod_github = https://github.com/ChefMooon/ubes-delight
mod_discord = https://discord.gg/mbuDBHHUws
mod_credits = ChefMooon, potatomadz

minecraft_supported_versions = 26.1,26.1.1,26.1.2
# STABLE, BETA, ALPHA
mod_version_type = STABLE
mod_build_number = 0
modrinth_project_id = PYjpoAys
curseforge_project_id = 903894

archives_base_name=ubesdelight
maven_group=com.chefMooon.ubesdelight

# Architectury
enabled_platforms = fabric
architectury_version = 9.1.12

# Loom
loom.ignoreDependencyLoomVersionValidation = true

parchment_version = 1.21.11:2025.12.20

fabric_loader_version = 0.19.2
fabric_api_version = 0.146.1+26.1.2

neoforge_version = 21.1.82
#1.20.1-47.2.1

# Farmer's Delight
fdrf_version = 26.1-3.6.3+refabricated
farmersdelight_version = 5962800

# Recipe Viewer Compat
# JEI, REI, EMI, RRV, or disabled
recipe_viewer = disabled
# https://modrinth.com/mod/jei/versions
jei_version = 29.5.0.26
# https://modrinth.com/mod/rei/versions
rei_version = 20.0.811
# https://modrinth.com/mod/emi/versions
emi_version = 1.1.12+1.21
# https://modrinth.com/mod/rrv
rrv_version = 8.0.1+26.1.2

# Appleskin
appleskin_fabric_version = mc1.21.6-3.0.7
appleskin_neoforge_version = mc1.21.6-3.0.7

# MidnightLib
midnightlib_fabric_version = 1.9.3+26.1-fabric
midnightlib_neoforge_version = 1.9.3+26.1-neoforge

# Mod Menu
mod_menu_version = 18.0.0-alpha.8

# WTHIT
wthitVersion = 19.0.1
badpacketsVersion = 0.12.2